apiVersion: v1
kind: Service
metadata:
  name: ureverse-be-service
spec:
  selector:
    app: ureverse-be
  ports:
    - protocol: TCP
      port: 80          # 클러스터 내 서비스 포트
      targetPort: 8080  # 컨테이너 포트
  type: LoadBalancer    # 클라우드 환경에서 외부 접속용
