apiVersion: apps/v1
kind: Deployment
metadata:
  name: ureverse-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ureverse
  template:
    metadata:
      labels:
        app: ureverse
    spec:
      containers:
      - name: ureverse
        image: taeyeon0319/ureverse-be:kty
        ports:
        - containerPort: 8080
